# Generated by Django 6.0.2 on 2026-02-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0004_interrogation_captain_outcome'),
        ('judiciary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtsession',
            name='convicted_suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_verdicts', to='investigation.suspect'),
        ),
    ]
