# Generated by Django 6.0.2 on 2026-02-22 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_scene_reported_at'),
        ('investigation', '0004_interrogation_captain_outcome'),
        ('judiciary', '0002_courtsession_convicted_suspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtsession',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_sessions', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='courtsession',
            name='convicted_suspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_verdicts', to='investigation.suspect'),
        ),
        migrations.AlterUniqueTogether(
            name='courtsession',
            unique_together={('case', 'convicted_suspect')},
        ),
    ]
