# Generated by Django 6.0 on 2026-02-21 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_image_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='cases.case')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('x', models.FloatField(default=50)),
                ('y', models.FloatField(default=50)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('evidence', 'Evidence'), ('suspect', 'Suspect')], default='note', max_length=20)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='investigation.detectiveboard')),
            ],
        ),
        migrations.CreateModel(
            name='BoardEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='investigation.boardnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='investigation.boardnode')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='investigation.detectiveboard')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('high_alert', 'High Alert'), ('arrested', 'Arrested'), ('cleared', 'Cleared'), ('criminal', 'Criminal')], default='wanted', max_length=20)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detective_score', models.PositiveSmallIntegerField(default=1)),
                ('sergeant_score', models.PositiveSmallIntegerField(default=1)),
                ('captain_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('captain_note', models.TextField(blank=True)),
                ('chief_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='cases.case')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detective_interrogations', to=settings.AUTH_USER_MODEL)),
                ('sergeant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sergeant_interrogations', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='investigation.suspect')),
            ],
        ),
    ]
