# Generated by Django 6.0.2 on 2026-02-22 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_scene_reported_at'),
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detective_reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('sergeant_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_submissions', to='cases.case')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detective_submissions', to=settings.AUTH_USER_MODEL)),
                ('sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sergeant_reviews', to=settings.AUTH_USER_MODEL)),
                ('suspects', models.ManyToManyField(related_name='submissions', to='investigation.suspect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
