# Generated by Django 6.0.2 on 2026-02-22 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_suspectsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogation',
            name='captain_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_interrogation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='captain_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='captain_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='chief_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_interrogation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='chief_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='chief_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='chief_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='detective_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='key_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='sergeant_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
