# Generated by Django 6.0.2 on 2026-02-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0003_interrogation_captain_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogation',
            name='captain_outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved To Trial'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
