# Generated by Django 6.0.2 on 2026-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0004_interrogation_captain_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogation',
            name='detective_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='sergeant_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
