# Generated by Django 6.0.2 on 2026-02-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailpayment',
            name='authority',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bailpayment',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bailpayment',
            name='sergeant_approved',
            field=models.BooleanField(default=False),
        ),
    ]
