# Generated by Django 6.0.2 on 2026-02-19 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('BAIL', 'Bail'), ('FINE', 'Fine')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cases.casesuspect')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('USEFUL', 'Marked as Useful'), ('REWARDED', 'Reward Claimed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('unique_reward_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reward_amount', models.DecimalField(decimal_places=0, default=0, help_text='Amount in Rials.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, help_text='The case this tip relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case')),
                ('informant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
