# Generated by Django 6.0.2 on 2026-02-20 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_complaint_case_case_complainants_and_more'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='case',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='informant',
        ),
        migrations.CreateModel(
            name='BailTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Amount in Rials')),
                ('description', models.CharField(max_length=255)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid/Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('case_suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_transactions', to='cases.casesuspect')),
            ],
        ),
        migrations.CreateModel(
            name='CivilianTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Details provided by the civilian')),
                ('status', models.CharField(choices=[('PENDING_OFFICER', 'Pending Officer Review'), ('PENDING_DETECTIVE', 'Pending Detective Review'), ('APPROVED', 'Approved (Reward Generated)'), ('REJECTED', 'Rejected')], default='PENDING_OFFICER', max_length=20)),
                ('unique_token', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('reward_amount', models.BigIntegerField(default=0, help_text='Amount in Rials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detective_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tips_detective', to=settings.AUTH_USER_MODEL)),
                ('officer_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tips_officer', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case')),
                ('related_suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips_against', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
