# Generated by Django 6.0.2 on 2026-02-19 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_data', models.JSONField(blank=True, default=dict, help_text='Stores positions of evidence, links, and notes.')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detective_board', to='cases.case')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sergeant_guilt_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detective_guilt_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('captain_approval', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('chief_approval', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('interrogation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assisting_detective', models.ForeignKey(limit_choices_to={'roles__access_level__gte': 40}, on_delete=django.db.models.deletion.PROTECT, related_name='detective_interrogations', to=settings.AUTH_USER_MODEL)),
                ('captain_approver', models.ForeignKey(blank=True, limit_choices_to={'roles__access_level__gte': 80}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_approvals', to=settings.AUTH_USER_MODEL)),
                ('case_suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='cases.casesuspect')),
                ('chief_approver', models.ForeignKey(blank=True, limit_choices_to={'roles__access_level__gte': 100}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_approvals', to=settings.AUTH_USER_MODEL)),
                ('interrogating_sergeant', models.ForeignKey(limit_choices_to={'roles__access_level__gte': 60}, on_delete=django.db.models.deletion.PROTECT, related_name='sergeant_interrogations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('GUILTY', 'Guilty'), ('NOT_GUILTY', 'Not Guilty')], max_length=15)),
                ('punishment_details', models.TextField(blank=True, help_text='Sentence or other punishment details, if guilty.')),
                ('trial_date', models.DateField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trial', to='cases.case')),
                ('judge', models.ForeignKey(limit_choices_to={'roles__name': 'Judge'}, on_delete=django.db.models.deletion.PROTECT, related_name='judged_trials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
