# Generated by Django 6.0.2 on 2026-02-20 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_complaint_case_case_complainants_and_more'),
        ('evidence', '0002_initial'),
        ('investigations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interrogation',
            name='assisting_detective',
        ),
        migrations.RemoveField(
            model_name='interrogation',
            name='captain_approver',
        ),
        migrations.RemoveField(
            model_name='interrogation',
            name='case_suspect',
        ),
        migrations.RemoveField(
            model_name='interrogation',
            name='chief_approver',
        ),
        migrations.RemoveField(
            model_name='interrogation',
            name='interrogating_sergeant',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='trial_date',
            new_name='date_started',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='case',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='punishment_details',
        ),
        migrations.AddField(
            model_name='trial',
            name='case_suspect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.casesuspect'),
        ),
        migrations.AddField(
            model_name='trial',
            name='court_transcripts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='date_concluded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='sentence_years',
            field=models.IntegerField(default=0, help_text='0 if not guilty or suspended'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials_judged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trial',
            name='verdict',
            field=models.CharField(blank=True, choices=[('GUILTY', 'Guilty'), ('NOT_GUILTY', 'Not Guilty'), ('MISTRIAL', 'Mistrial')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EvidenceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(choices=[('CIRCUMSTANTIAL', 'Circumstantial'), ('CORROBORATING', 'Corroborating'), ('DIRECT', 'Direct Link')], default='CIRCUMSTANTIAL', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Detective's notes on how this evidence connects to the suspect.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_connections', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_connections', to='evidence.evidence')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='cases.casesuspect')),
            ],
            options={
                'unique_together': {('suspect', 'evidence')},
            },
        ),
        migrations.DeleteModel(
            name='DetectiveBoard',
        ),
        migrations.DeleteModel(
            name='Interrogation',
        ),
    ]
