# Generated by Django 6.0.2 on 2026-02-20 23:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_casesuspect_options_and_more'),
        ('evidence', '0003_witnessstatement_alter_evidence_options_and_more'),
        ('investigations', '0002_remove_interrogation_assisting_detective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='court_transcripts',
            new_name='judge_notes',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='date_concluded',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='date_started',
        ),
        migrations.AddField(
            model_name='trial',
            name='trial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='case_suspect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.casesuspect'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trial',
            name='sentence_years',
            field=models.IntegerField(default=0, help_text='Prison sentence in years (if guilty)'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='verdict',
            field=models.CharField(choices=[('GUILTY', 'Guilty'), ('NOT_GUILTY', 'Not Guilty'), ('MISTRIAL', 'Mistrial')], max_length=20),
        ),
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detective_board', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(default=0.0)),
                ('y_position', models.FloatField(default=0.0)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_placements', to='evidence.evidence')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='investigations.detectiveboard')),
            ],
        ),
        migrations.CreateModel(
            name='BoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='red', max_length=20)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='investigations.boarditem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='investigations.boarditem')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='investigations.detectiveboard')),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detective_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detective_notes', models.TextField(blank=True)),
                ('sergeant_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sergeant_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_approvals', to=settings.AUTH_USER_MODEL)),
                ('case_suspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interrogation', to='cases.casesuspect')),
                ('chief_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_approvals', to=settings.AUTH_USER_MODEL)),
                ('detective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detective_interrogations', to=settings.AUTH_USER_MODEL)),
                ('sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sergeant_interrogations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EvidenceConnection',
        ),
    ]
