# Generated by Django 6.0.2 on 2026-02-19 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_collected', models.DateTimeField()),
                ('evidence_type', models.CharField(choices=[('TESTIMONY', 'Witness Testimony'), ('BIOLOGICAL', 'Biological/Medical'), ('VEHICLE', 'Vehicle'), ('ID_DOCUMENT', 'ID Document'), ('OTHER', 'Other')], max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Biological',
            fields=[
                ('evidence_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evidence/biological/')),
                ('coroner_report', models.TextField(blank=True, help_text='Findings from the coroner.')),
                ('identity_bank_result', models.TextField(blank=True, help_text='Results from the identity bank query.')),
            ],
        ),
        migrations.CreateModel(
            name='IDDocument',
            fields=[
                ('evidence_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('document_type', models.CharField(help_text="e.g., Driver's License, Passport", max_length=100)),
                ('owner_full_name', models.CharField(max_length=255)),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Key-value pairs of document data.')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('evidence_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('transcription', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='evidence/testimony/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('evidence_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='VIN or other serial number', max_length=50, null=True)),
            ],
        ),
    ]
