# Generated by Django 6.0.2 on 2026-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='witnessevidence',
            name='media_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
