# Generated by Django 6.0.2 on 2026-02-19 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimony',
            name='witness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testimonies', to=settings.AUTH_USER_MODEL),
        ),
    ]
