# Generated by Django 6.0.2 on 2026-02-20 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_crimescenereport_reporting_officer'),
        ('evidence', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WitnessStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='statements/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-date_collected']},
        ),
        migrations.AlterField(
            model_name='biological',
            name='evidence_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='date_collected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='iddocument',
            name='evidence_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='evidence_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='evidence_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('license_plate__isnull', False), ('serial_number__isnull', True)), models.Q(('license_plate__isnull', True), ('serial_number__isnull', False)), _connector='OR'), name='vehicle_plate_xor_serial'),
        ),
        migrations.AddField(
            model_name='witnessstatement',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_statements', to='cases.case'),
        ),
        migrations.AddField(
            model_name='witnessstatement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='witnessstatement',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_statements', to=settings.AUTH_USER_MODEL),
        ),
    ]
