# Generated by Django 6.0.2 on 2026-02-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Case Title')),
                ('description', models.TextField(verbose_name='Case Summary Description')),
                ('crime_level', models.IntegerField(choices=[(4, 'Critical'), (3, 'Level 1 (High)'), (2, 'Level 2 (Medium)'), (1, 'Level 3 (Low)')], verbose_name='Crime Level')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('OPEN', 'Open for Investigation'), ('INVEST_DONE', 'Investigation Complete'), ('AWAITING_TRIAL', 'Awaiting Trial'), ('CLOSED_GUILTY', 'Closed (Conviction)'), ('CLOSED_NOT_GUILTY', 'Closed (Acquittal)'), ('CLOSED_COLD', 'Closed (Cold Case)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSuspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WANTED', 'Wanted'), ('HIGHLY_WANTED', 'Highly Wanted'), ('IN_CUSTODY', 'In Custody'), ('BAIL', 'Released on Bail'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted')], default='WANTED', max_length=20)),
                ('date_marked_wanted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case Suspects',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='Complaint Details')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved (Case Created)'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived (Rejected 3 times)')], default='PENDING', max_length=20)),
                ('rejection_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeSceneReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_datetime', models.DateTimeField()),
                ('location_details', models.CharField(max_length=255)),
                ('report_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
