# Generated by Django 6.0.2 on 2026-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecomplainant',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='casecomplainant',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casecomplainant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='complaintsubmission',
            name='last_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaintsubmission',
            name='stage',
            field=models.CharField(choices=[('to_cadet', 'To Cadet'), ('to_officer', 'To Officer'), ('returned_to_complainant', 'Returned To Complainant'), ('returned_to_cadet', 'Returned To Cadet'), ('formed', 'Formed'), ('voided', 'Voided')], default='to_cadet', max_length=30),
        ),
    ]
