# Generated by Django 6.0.2 on 2026-02-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_casecomplainant_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='scene_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
