# Generated by Django 6.0.2 on 2026-02-20 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='case',
        ),
        migrations.AddField(
            model_name='case',
            name='complainants',
            field=models.ManyToManyField(blank=True, related_name='filed_cases', to=settings.AUTH_USER_MODEL, verbose_name='Complainants'),
        ),
        migrations.AddField(
            model_name='casesuspect',
            name='captain_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casesuspect',
            name='chief_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casesuspect',
            name='date_arrested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casesuspect',
            name='detective_notes',
            field=models.TextField(blank=True, help_text='Interrogation summary by Lead Detective'),
        ),
        migrations.AddField(
            model_name='casesuspect',
            name='detective_score',
            field=models.PositiveIntegerField(default=0, help_text='Guilt probability score (1-10)'),
        ),
        migrations.AddField(
            model_name='casesuspect',
            name='sergeant_notes',
            field=models.TextField(blank=True, help_text='Review notes by Sergeant'),
        ),
        migrations.AddField(
            model_name='casesuspect',
            name='sergeant_score',
            field=models.PositiveIntegerField(default=0, help_text='Validation score (1-10)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='cadet_message',
            field=models.TextField(blank=True, null=True, verbose_name="Cadet's Rejection Message"),
        ),
        migrations.AddField(
            model_name='complaint',
            name='target_case',
            field=models.ForeignKey(blank=True, help_text='If this complaint belongs to an existing case, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_complaints', to='cases.case'),
        ),
        migrations.AddField(
            model_name='crimescenereport',
            name='status',
            field=models.CharField(choices=[('PENDING_SUPERIOR', 'Pending Superior Approval'), ('APPROVED', 'Approved (Case Created)'), ('REJECTED', 'Rejected')], default='PENDING_SUPERIOR', max_length=25),
        ),
        migrations.AlterField(
            model_name='case',
            name='suspects',
            field=models.ManyToManyField(blank=True, related_name='suspected_in_cases', through='cases.CaseSuspect', through_fields=('case', 'suspect'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casesuspect',
            name='status',
            field=models.CharField(choices=[('WANTED', 'Wanted'), ('HIGHLY_WANTED', 'Highly Wanted (Critical)'), ('IN_CUSTODY', 'In Custody (Interrogation Pending)'), ('PENDING_SGT', 'Pending Sergeant Review'), ('RELEASED_EVIDENCE', 'Released (Insufficient Evidence)'), ('SENT_TO_TRIAL', 'Sent to Trial'), ('BAIL', 'Released on Bail'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted')], default='WANTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING_CADET', 'Pending Cadet Review'), ('PENDING_OFFICER', 'Pending Officer Review'), ('RETURNED_TO_COMPLAINANT', 'Returned to Complainant (Defect)'), ('RETURNED_TO_CADET', 'Returned to Cadet (Defect)'), ('APPROVED', 'Approved (Case Created/Joined)'), ('ARCHIVED', 'Archived (Nullified - 3 Strikes)')], default='PENDING_CADET', max_length=200),
        ),
        migrations.AlterField(
            model_name='crimescenereport',
            name='reporting_officer',
            field=models.ForeignKey(limit_choices_to={'role__access_level__gte': 20}, on_delete=django.db.models.deletion.PROTECT, related_name='crime_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
