# Generated by Django 6.0.2 on 2026-02-20 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_complaint_case_case_complainants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimescenereport',
            name='reporting_officer',
            field=models.ForeignKey(limit_choices_to={'roles__access_level__gte': 20}, on_delete=django.db.models.deletion.PROTECT, related_name='crime_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
