# Generated by Django 6.0.2 on 2026-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_crimescenereport_reporting_officer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casesuspect',
            options={},
        ),
        migrations.RenameField(
            model_name='casesuspect',
            old_name='date_arrested',
            new_name='wanted_since',
        ),
        migrations.RemoveField(
            model_name='casesuspect',
            name='captain_approved_by',
        ),
        migrations.RemoveField(
            model_name='casesuspect',
            name='chief_approved_by',
        ),
        migrations.RemoveField(
            model_name='casesuspect',
            name='date_marked_wanted',
        ),
        migrations.RemoveField(
            model_name='casesuspect',
            name='detective_notes',
        ),
        migrations.RemoveField(
            model_name='casesuspect',
            name='detective_score',
        ),
        migrations.RemoveField(
            model_name='casesuspect',
            name='sergeant_notes',
        ),
        migrations.RemoveField(
            model_name='casesuspect',
            name='sergeant_score',
        ),
        migrations.AlterField(
            model_name='casesuspect',
            name='status',
            field=models.CharField(choices=[('UNDER_INVESTIGATION', 'Under Investigation'), ('WAITING_SERGEANT', 'Waiting Sergeant Approval'), ('SERGEANT_APPROVED', 'Sergeant Approved'), ('WAITING_CAPTAIN', 'Waiting Captain Approval'), ('TRIAL_READY', 'Ready for Trial'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted'), ('MISTRIAL', 'Mistrial'), ('RELEASED_ON_BAIL', 'Released on Bail')], default='UNDER_INVESTIGATION', max_length=30),
        ),
    ]
