# Generated by Django 6.0.2 on 2026-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_initial_roles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolerequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='rolerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'requested_role'), name='unique_pending_role_request'),
        ),
    ]
